apiVersion: v2
appVersion: "1.0"
description: A Helm chart for et-sya-api Java API
name: et-sya-api
home: https://github.com/hmcts/et-sya-api
version: 0.0.1
maintainers:
  - name: HMCTS et team
dependencies:
  - name: java
    version: 3.6.0
    repository: '@hmctspublic'
