idam:
  api:
    url: http://localhost:5062
    jwksUrl: http://localhost:5062/o/jwks
  s2s-auth:
    url: http://localhost:8489
    secret: AAAAAAAAAAAAAAAA

core_case_data:
  api:
    url: http://localhost:4452

caseWorkerUserName: ${CASEWORKER_USER_NAME:user_name}
caseWorkerPassword: ${CASEWORKER_PASSWORD:password}
